server:
  port: 8080

spring:
  application:
    name: durable-reminders
  datasource:
    url: jdbc:h2:file:./data/reminders_db;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  scheduler:
    polling-rate-ms: 500
    claim-lease-seconds: 60
    max-retries: 3
    base-retry-backoff-seconds: 5